export const env = {
	NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV as string,
	NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL as string,
	NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL as string,
	NEXT_PUBLIC_AI_AGENT_API_URL: process.env.NEXT_PUBLIC_AI_AGENT_API_URL as string,
	NEXT_PUBLIC_REOWN_PROJECT_ID: process.env.NEXT_PUBLIC_REOWN_PROJECT_ID as string,
	NEXT_PUBLIC_CMC_API: process.env.NEXT_PUBLIC_CMC_API as string,
	NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET as string,
	NEXTAUTH_URL: process.env.NEXTAUTH_URL as string,
	NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_BUFFER: process.env
		.NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_BUFFER as string,
	NEXT_PUBLIC_DD_APP_ID: process.env.NEXT_PUBLIC_DD_APP_ID as string,
	NEXT_PUBLIC_DD_CLIENT_TOKEN: process.env.NEXT_PUBLIC_DD_CLIENT_TOKEN as string,
	NEXT_PUBLIC_DD_SERVICE_NAME: process.env.NEXT_PUBLIC_DD_SERVICE_NAME as string,
	NEXT_PUBLIC_DD_SITE: process.env.NEXT_PUBLIC_DD_SITE as string,
	NEXT_PUBLIC_DD_LOG_IN_DEV: process.env.NEXT_PUBLIC_DD_LOG_IN_DEV as string,
	NEXT_PUBLIC_VAULT_FACTORY_CONTRACT_ADDRESS: process.env
		.NEXT_PUBLIC_VAULT_FACTORY_CONTRACT_ADDRESS as string,
};
